apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.14.0 
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        
        persistence:
          enabled: true
          size: 20Gi # 필요에 따라 크기 조정
        
        protocol: http
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
