apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.48.0
    helm:
      values: |
        image:
          repository: cr.fluentbit.io/fluent/fluent-bit
          pullPolicy: IfNotPresent

        rbac:
          create: true

        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush {{ .Values.flush | default 1 }}
                Log_Level {{ .Values.logLevel | default "info" }}
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort | default 2020 }}
                Health_Check On

          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 5MB
                Skip_Long_Lines On

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On

            [FILTER]
                Name grep
                Match kube.*
                # kubernetes.labels.app 필드에 'spring' 문자열이 포함된 로그만 허용합니다.
                Regex kubernetes.labels.app spring

          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host my-es-cluster-es-http.logging.svc.cluster.local
                Port 9200
                Logstash_Format On
                Logstash_Prefix fluent-bit
                Replace_Dots On
                Retry_Limit False

          customParsers: |
            [PARSER]
                Name docker_no_time
                Format json
                Time_Keep Off
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L

        logLevel: info

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true