apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.48.0
    helm:
      values: |
        # Deployment으로 변경 (DaemonSet이 더 이상 필요 없음)
        kind: Deployment
        replicaCount: 2

        image:
          repository: cr.fluentbit.io/fluent/fluent-bit
          pullPolicy: IfNotPresent

        rbac:
          create: true

        config:
          service: |
            [SERVICE]
                Flush           5
                Log_Level       info
                Parsers_File    parsers.conf


          inputs: |
            [INPUT]
                Name            http
                Host            0.0.0.0
                Port            8888
                Tag             http.spring.log

          filters: |
            [FILTER]
                Name nest
                Match *
                Operation lift
                Nested_under kubernetes
                Add_prefix kubernetes_

          outputs: |
            [OUTPUT]
                Name            es
                Match           *
                Host            my-es-cluster-es-http.logging.svc.cluster.local
                Port            9200
                Logstash_Format On
                Logstash_Prefix fluent-bit-spring-direct
                Replace_Dots    On
                Retry_Limit     False
                Buffer_Size     64k
                tls             On
                tls.verify      Off
                HTTP_User       elastic
                HTTP_Passwd     ${ELASTIC_PASSWORD}
                Suppress_Type_Name On

        # 비밀번호 주입은 동일하게 사용
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-es-cluster-es-elastic-user
                key: elastic

        # Service: 8888 포트를 노출하도록 변경
        service:
          type: ClusterIP # 외부 노출은 Ingress로 처리
          ports:
            - port: 8888
              targetPort: 8888
              protocol: TCP
              name: http

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true