# Git 저장소의 fluent-bit.yaml 파일
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.48.0
    helm:
      values: |
        kind: Deployment
        replicaCount: 2
        image:
          repository: cr.fluentbit.io/fluent/fluent-bit
          pullPolicy: IfNotPresent
        rbac:
          create: true
        config:
          service: |
            [SERVICE]
                Flush           5
                Log_Level       info
                Parsers_File    parsers.conf
                HTTP_Server     On
                HTTP_Listen     0.0.0.0
                HTTP_Port       2020
                Health_Check    On
          inputs: |
            [INPUT]
                Name            http
                Host            0.0.0.0
                Port            8888
                Tag             http.spring.log
          filters: |
            [FILTER]
                Name nest
                Match *
                Operation lift
                Nested_under kubernetes
                Add_prefix kubernetes_
          outputs: |
            [OUTPUT]
                Name            es
                Match           *
                Host            my-es-cluster-es-http.logging.svc.cluster.local
                Port            9200
                Logstash_Format On
                Logstash_Prefix fluent-bit-spring-direct
                Replace_Dots    On
                Retry_Limit     False
                Buffer_Size     64k
                tls             On
                tls.verify      Off
                HTTP_User       elastic
                HTTP_Passwd     ${ELASTIC_PASSWORD}
                Suppress_Type_Name On
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-es-cluster-es-elastic-user
                key: elastic

        service:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true