apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: witt-bare-wildcard-cert
  namespace: istio-system
spec:
  dnsNames:
    - '*.jalju.com'
    - 'jalju.com'
  issuerRef:
    kind: ClusterIssuer
    name: le-wildcard-issuer
  secretName: wildcard-jalju-com-tls