apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-wildcard-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dlckswn334@ajou.ac.kr
    privateKeySecretRef:
      name: le-wildcard-issuer
    solvers:
      - dns01:
          route53:
            region: ap-northeast-2
            accessKeyIDSecretRef:
              name: aws-route53-creds
              key: access-key
            secretAccessKeySecretRef:
              name: aws-route53-creds
              key: secret-access-key