apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argocd/argocd-server-metrics.yaml
  - ./argocd/argocd-repo-server-metrics.yaml
  - ./argocd/argocd-metrics.yaml
  - ./argocd/argocd-dex-server.yaml