apiVersion: v1
kind: Pod
metadata:
  name: acc-ai-pod         
  labels:
    app: acc-ai             
spec:
  containers:
  - name: acc-ai-container 
    image: dlckswn334/acc-ai:latest 
    imagePullPolicy: IfNotPresent   
    
    ports:
    - containerPort: 8080     
      name: http
      protocol: TCP

    resources:
      requests:
        cpu: "100m"         
        memory: "256Mi"    
      limits:   
        cpu: "500m"         
        memory: "512Mi"    

  restartPolicy: Always 