apiVersion: v1
kind: Service
metadata:
  name: argocd-external
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
    - port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - argocd.bare.witt.kr
      secretName: witt-bare-wildcard-cert
  rules:
    - host: argocd.bare.witt.kr
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: argocd-external
                port:
                  number: 80