apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "argocd.jalju.com"
        - "grafana.jalju.com"
        - "loki.jalju.com"
        - "ngrinder.jalju.com"
        - "sentry.jalju.com"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "argocd.jalju.com"
        - "grafana.jalju.com"
        - "loki.jalju.com"
        - "ngrinder.jalju.com"
        - "sentry.jalju.com"
      tls:
        mode: SIMPLE
        credentialName: wildcard-jalju-com-tls
