apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ui.charts.kafbat.io/
    chart: kafka-ui
    targetRevision: 1.5.0
    helm:
      values: |
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: "My Kafka Cluster" 
                bootstrapServers: "bitnami-kafka.kafka.svc.cluster.local:9092"

          service:
            type: NodePort
            port: 8080
            nodePort: 30000
            
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-ui 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # 대상 네임스페이스가 없을 경우 자동으로 생성합니다.