apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: kube-prometheus-stack
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 45.6.0
    helm:
      skipCrds: true
      values: |-
        prometheus:
          prometheusSpec:
            serviceMonitorSelector:
              matchLabels:
                prometheus: argo-cd-grafana
            additionalScrapeConfigs: |
              - job_name: 'argocd-metrics'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['argocd-metrics.argocd.svc.cluster.local:8082, argocd-server-metrics.argocd.svc.cluster.local:8083, argocd-notifications-controller-metrics.argocd.svc.cluster.local:9001']

              - job_name: 'alertManager'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['alertmanager-operated.monitoring.svc.cluster.local:9093']

              - job_name: 'nodeExporter'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['prometheus-node-exporter.monitoring.svc.cluster.local:9100']
              
               - job_name: "spring-actuator"
                metrics_path: "/v1/actuator/prometheus"
                scrape_interval: 1m
                static_configs:
                  - targets: ["https://dev-backend.dev.witt.kr/v1/actuator/health"]
                tls_config:
                  insecure_skip_verify: true
        alertmanager:
          enabled: true
        nodeExporter:
          enabled: false
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true