apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 21.1.6 
    helm:
      values: |
        auth:
          enabled: true
            password: "qwe1356@" 

        master:
          service:
            type: NodePort 
            ports:
              redis: 6379 
            nodePorts:
              redis: "30379" 
        
        replica:
          service:
            type: ClusterIP # 기본값
            ports:
              redis: 6379
  destination:
    server: https://kubernetes.default.svc
    namespace: redis # Redis를 설치할 네임스페이스 (예: redis, cache 등)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true