apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://sentry-kubernetes.github.io/charts
    chart: sentry
    targetRevision: 25.13.0
    helm:
      values: |-
        nginx:
          enabled: false
        ingress:
          enabled: true
          regexPathStyle: nginx
          alb:
            httpRedirect: false
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/use-regex: "true"
            nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
            nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
          hostname: sentry.bare.witt.kr
          tls:
            - secretName: witt-bare-wildcard-cert
              hosts:
                - sentry.bare.witt.kr
                
  destination:
    server: https://kubernetes.default.svc
    namespace: sentry
  syncPolicy:
    automated:
      prune: true