apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://sentry-kubernetes.github.io/charts
    chart: sentry
    targetRevision: 25.13.0
    helm:
      values: |-
        nginx:
          enabled: false
        ingress:
          enabled: false
        externalPostgresql:
          host: database-host
          port: 5432
          username: postgres
          password: ""
          database: sentry
        
  destination:
    server: https://kubernetes.default.svc
    namespace: sentry
  syncPolicy:
    automated:
      prune: true