apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./kafka/application.yml
- ./valkey/application.yml
- ./kafka-ui/application.yml
- ./postgre/application.yml
- ./application/acc-ai-pod.yaml
# - ./pgadmin/application.yml