apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./flux/application.yaml
  - ./vault/application.yaml
  - ./keycloak/application.yaml
  - ./prometheus/application.yaml
  - ./prometheus-operator-crds/application.yaml
