apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://grafana.github.io/helm-charts  
    chart: k6-operator  
    targetRevision: 3.9.0
  destination:
    server: https://kubernetes.default.svc  
    namespace: k6
  syncPolicy:
    automated:  
      prune: true
