apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 32.2.8
helm:
  values: |
    sasl:
      client:
        users:
          - "user1" 
        passwords:
          - "qwe1356@"

    listeners:
      client: 
        name: CLIENT
        containerPort: 9092
        protocol: SASL_PLAINTEXT 
      external: 
        name: EXTERNAL
        containerPort: 9095 
        protocol: SASL_PLAINTEXT 

    externalAccess:
      enabled: true
      broker:
        service:
          type: NodePort
          ports:
            external: 9095 
          nodePorts:
            - 30095 
            - 30096 
            - 30097 
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
