apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 28.1.2 # Bitnami Kafka 차트의 특정 버전을 명시하는 것이 좋습니다. 최신 버전은 ArtifactHub에서 확인하세요.
    # helm:
    #   values: |
    #     # 여기에 필요한 경우 Bitnami Kafka 차트의 values.yaml 내용을 커스터마이징하여 추가합니다.
    #     # 예시:
    #     # replicaCount: 3
    #     # persistence:
    #     #   enabled: true
    #     #   size: 10Gi
    #     # zookeeper:
    #     #   replicaCount: 3
    #     #   persistence:
    #     #     enabled: true
    #     #     size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true