apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-kafka
  namespace: argocd
spec:
  project: default
  source: # `source` 필드 시작
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 32.2.8
    helm:
      values: |
        # SASL 클라이언트 사용자 및 비밀번호
        sasl:
          client:
            users:
              - "user1" 
            passwords:
              - "qwe1356@" 

        # 리스너 설정
        listeners:
          client: 
            name: CLIENT
            containerPort: 9092 
            protocol: SASL_PLAINTEXT 
          external:
            name: EXTERNAL
            containerPort: 9095 
            protocol: SASL_PLAINTEXT

        externalAccess:
          enabled: true
          controller: 
            service:
              type: NodePort 
              ports:
                external: 9095 
              nodePorts:
                - 30095 
                - 30096 
                - 30097 
              domain: 172.31.0.20
              
          broker: 
            service:
              type: ClusterIP
              ports:
                external: 9094 
              nodePorts: [] 
  destination: 
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true