apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 32.2.8
    helm:
      values: |
        auth:
          sasl:
            enabled: false 
            interBrokerMechanism: PLAINTEXT
            clientUsers: []
        listeners:
          client: 
            protocol: PLAINTEXT
            port: 9092
        advertisedListeners:
          - PLAINTEXT://bitnami-kafka.kafka.svc.cluster.local:9092 
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true