apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: witt-bare-wildcard-cert
  namespace: cert-manager
spec:
  dnsNames:
    - '*.bare.witt.kr'
  issuerRef:
    kind: ClusterIssuer
    name: le-wildcard-issuer
  secretName: witt-bare-wildcard-cert