apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bear-feast-api
  namespace: shared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aods-vault
    kind: ClusterSecretStore
  target:
    name: bear-feast-api-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: aods/apps/shared/bear-feast-api/prod
