apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespcae: argocd
spec:
  project: default
  source:
    repoURL: https://helm.influxdata.com/
    chart: influxdb
    targetRevision: 4.12.5
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  syncPolicy:
    automated:
      prune: true