{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "my-workout",
  "resources": ["config.yaml", "storage.yaml", "deployment.yaml", "service.yaml", "backup.yaml"],
  "images": [{"name": "ghcr.io/jalju0804/my-workout", "newTag": "pending-first-build"}]
}
