{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "my-workout",
  "resources": [
    "config.yaml",
    "storage.yaml",
    "deployment.yaml",
    "service.yaml",
    "backup.yaml"
  ],
  "images": [
    {
      "name": "ghcr.io/jalju0804/my-workout",
      "newTag": "sha-6b4fe656f9927b991ebe711887a4893178c56a1f"
    }
  ]
}
