{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "my-workout",
  "resources": [
    "config.yaml",
    "storage.yaml",
    "deployment.yaml",
    "service.yaml",
    "backup.yaml"
  ],
  "images": [
    {
      "name": "ghcr.io/jalju0804/my-workout",
      "newTag": "sha-934c210aacb5e28cad3237b13d92c6925e23e775"
    }
  ]
}
